### ISSUE TITLE
Uncaught Error: Cannot find module 'flat'

### ISSUE THREAD

**Issue by TangSirOnGit** [KunihikoKido/atom-flatten-json#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.8
**System**: Ubuntu 15.04
**Thrown From**: [flatten-json](https://github.com/KunihikoKido/atom-flatten-json) package, v0.1.4
### Stack Trace

Uncaught Error: Cannot find module 'flat'

```
At module.js:330

Error: Cannot find module 'flat'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.FlattenJson.flatten (/home/laimingjiang/下载/atom-flatten-json-0.1.4/lib/flatten-json.coffee:26:16)
  at atom-workspace.subscriptions.add.atom.commands.add.flatten-json:unflatten (/home/laimingjiang/下载/atom-flatten-json-0.1.4/lib/flatten-json.coffee:13:90)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:47.1.0 flatten-json:flatten (atom-text-editor.editor)
     -0:39.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:34.3.0 flatten-json:flatten (atom-text-editor.editor)
     -0:23 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:15.9.0 editor:fold-current-row (atom-text-editor.editor.is-focused)
     -0:12 editor:unfold-current-row (atom-text-editor.editor.is-focused)
  3x -0:11.7.0 editor:fold-current-row (atom-text-editor.editor.is-focused)
     -0:09.7.0 editor:unfold-current-row (atom-text-editor.editor.is-focused)
     -0:09.5.0 editor:fold-current-row (atom-text-editor.editor.is-focused)
     -0:09.4.0 editor:unfold-current-row (atom-text-editor.editor.is-focused)
     -0:09.2.0 editor:fold-current-row (atom-text-editor.editor.is-focused)
     -0:09.1.0 editor:unfold-current-row (atom-text-editor.editor.is-focused)
     -0:05.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 flatten-json:unflatten (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
flatten-json, v0.1.4
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by KunihikoKido** [comment]
Hi.

Please try the editor after restart (or Window reload).
